"""add message deleted_at and room_member cleared_at

Revision ID: 3a8b1874da18
Revises: a397ec331cc4
Create Date: 2026-08-01 20:26:54.466095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8b1874da18'
down_revision: Union[str, None] = 'a397ec331cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('room_members', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'cleared_at')
    op.drop_column('messages', 'deleted_at')
    # ### end Alembic commands ###
