"""add encrypted_private_key and key_salt to users

Revision ID: a397ec331cc4
Revises: f4d8f195a170
Create Date: 2026-08-01 17:27:29.854106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a397ec331cc4'
down_revision: Union[str, None] = 'f4d8f195a170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_private_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('key_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key_salt')
    op.drop_column('users', 'encrypted_private_key')
    # ### end Alembic commands ###
