"""add public_key to users

Revision ID: f4d8f195a170
Revises: 92aad1b0c95f
Create Date: 2026-08-01 06:54:43.945152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d8f195a170'
down_revision: Union[str, None] = '92aad1b0c95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###
